name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 0.7.0
homepage: https://github.com/hivedb/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^1.1.6
  source_gen:
  hive: ">=1.3.0 <2.0.0"
  analyzer:
  dartx: ^0.2.0

dev_dependencies:
  test: ^1.6.4
  build_test: any
  build_runner: any
  pedantic: '1.7.0'
